server:
  port: 8021

spring:
  application:
    name: account-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://116.62.14.208:3306/account?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xiaotang.springaccount
#  configuration:
#    interceptors:
#      - com.xiaotang.springorder.interceptor.InsertInterceptor



logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
