server:
  port: 8010
spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  server:
    port: 8011
  endpoints:
    web:
      exposure:
        include: "*"