server:
  port: 8081

spring:
  application:
    name: gateway-service
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true